### ISSUE TITLE
Allow phrase with space to be selected.

### ISSUE THREAD

**Issue by dthies** [marcusgreen/moodle-qtype_wordselect#1]
There should be a method to bind words into a phrase by escaping a space or providing an alternate character for spaces. Parser could recognize backslash space or _ or ~ as a space betweens words that are bound together rather than a separation between them

**Comment by dthies** [comment]
A simple way to do this may be to allow the separator between words to be selectable as with the other delimiters.

**Comment by marcusgreen** [comment]
I have been experimenting with a user interface for people creating questions to be able to select words and spaces. The code for that is actually aimed at my gapfill question type but it might be repurposed for this question type. So in the editor you would select a bunch of text, click on it and get a dialog that would allow you to bind it all together. My ambition is to make the question type very easy to use and to keep any syntax to the very bare minimum. 

However I have put a great deal of thought into the issues over a few years and for the moment I am am going to concentrate on getting the current functionality stable and usable before going into this concept in great depth.
Have you had a look in the Git Wiki for this (click the wiki icon above this)

**Comment by marcusgreen** [comment]
Thanks for your feedback Daniel. I just noticed this was still open. This capability was introduced with version 2.0 which you can see described in the changelog.
https://github.com/marcusgreen/moodle-qtype_wordselect/blob/master/changelog.md
