### ISSUE TITLE
Undefined Offset on line 284 in question.php

### ISSUE THREAD

**Issue by dustinbrisebois** [marcusgreen/moodle-qtype_wordselect#15]
Notice: Undefined offset: 26 in /var/www/data/pvschools/public_html/moodle/question/type/wordselect/question.php on line 286
Exception - Call to a member function get_without_delim() on null

As per line:
https://github.com/marcusgreen/moodle-qtype_wordselect/blob/37f509bec713566578df164a1111e403d4b4b946/question.php#L284

Should be something more similar to this:
```
if (isset($allwords[substr($index, 1)])) {
          $summary .= " " . $allwords[substr($index, 1)]->get_without_delim() . " ";
} else {
          return '';
}
```

Where the assumption that the item exists in the array - if it doesn't it faults out.

**Comment by marcusgreen** [comment]
Thanks Dustin, Can you tell me how to reproduce this so that when I update the code I can include an automated test for it?

**Comment by marcusgreen** [comment]
would you email me at marcusgreen at mailbox.org

**Comment by dustinbrisebois** [comment]
@marcusgreen were you able to sort this out?

**Comment by marcusgreen** [comment]
Hi Dustin
I was never able to reproduce this but I have just done a commit which I think is a slightly more concise version of your suggestion just in case. Please correct me if you think it doesn't do what you expect. 
https://github.com/marcusgreen/moodle-qtype_wordselect/commit/daf2e6401db65c92a0c51f06bf4a274369061021
I am currently working on a branch that will support the mobile app so this will get pushed to the plugins database as part of that release.
