### ISSUE TITLE
cannot upgrade to version 2018122800 

### ISSUE THREAD

**Issue by rezeau** [marcusgreen/moodle-qtype_wordselect#16]
cannot upgrade to version **2018122800** I get a bunch of warnings:
Warning: mkdir(): Permission denied in C:\xampp\htdocs\moodle\lib\classes\update\code_manager.php on line 555

Warning: rename(C:\xampp\moodledata/localcache\c590b509-b5a4-4f0b-b08e-30a1062b323b\15ac7258-b9f4-4e9a-ae00-44cb187d0363/wordselect/questiontype.php,C:\xampp\htdocs\moodle/question/type/wordselect/questiontype.php): Acc�s refus�. (code: 5) in C:\xampp\htdocs\moodle\lib\classes\update\code_manager.php on line 557

Warning: mkdir(): Permission denied in C:\xampp\htdocs\moodle\lib\classes\update\code_manager.php on line 555
... and many more

**Comment by marcusgreen** [comment]
Can you tell me the version of wordselect you are moving from?. I have a windows machine I will attempt to reproduce this error on xampp.

**Comment by rezeau** [comment]
I finally completely removed the previous version and installed version 2018122800 from scratch and now it's working

**Comment by marcusgreen** [comment]
I have seen issues like this in the past with other plugins that were fixed by either purging caches or re-installing. I don't think the issue came from code in the plugin so I will close this issue. If it re-occurs please open/post a new issue. Many thanks for your feedback.
