### ISSUE TITLE
The file selection.js should be transferred to an amd module

### ISSUE THREAD

**Issue by mkassaei** [marcusgreen/moodle-qtype_wordselect#18]
The selection.js file in question/type/wordselect uses jquery and seems to cause problem when more than one script using jquery on a page.

I will be working on this

**Comment by marcusgreen** [comment]
Thanks for letting me know. Could you give me more details as it might be an issue with the companion question type gapfill.

**Comment by marcusgreen** [comment]
Hi mkassel, I didn't read the full header of your issue when I last looked. Now I understand it and doing that is quite clearly a very good thing.

**Comment by marcusgreen** [comment]
I have added some code to convert selection to use amd, let me know what you think. Improvements gratefully accepted.

**Comment by timhunt** [comment]
This is done, right? I think it can be closed.

**Comment by marcusgreen** [comment]
Done, closing
