### ISSUE TITLE
Mix non selectable text. 

### ISSUE THREAD

**Issue by dthies** [marcusgreen/moodle-qtype_wordselect#2]
It would be good to have more flexibility in the syntax to mix selectable words with non selectable. For example 

Select the mammals from the animals in the sentence:
The cat chased a bird and a butterfly.

**Comment by marcusgreen** [comment]
Yes indeed, I was considering an additiional delimitchar and at the moment I was considering the asterisk as a default. So *The cat chased a* bird *and a *butterfly* would mean only bird or butterfly would be selectable.

**Comment by marcusgreen** [comment]
Hi Daniel
I have set up a course with a version of the Wordselect question type that which allows the mixing of selectable and non selectable words and also the marking of multiple words as selectable. You can see it at 

http://vledevelop.co.uk/moodle/
You can log in as a teacher as 
username:t1 password:test

**Comment by dthies** [comment]
Hi Marcus,
That looks great. The choice for syntax is very convenient, and it will definitely produce useful questions.
