### ISSUE TITLE
Wordselect breaks if Moodle option 'forceclean' is turned on (e.g. View as Student)

### ISSUE THREAD

**Issue by HuongNV13** [marcusgreen/moodle-qtype_wordselect#22]
Hi @marcusgreen,

I found an issue related to this question type as below:

The WordSelect will be break if Moodle option 'forceclean' is turned on. Now, it's only the experimental setting, but in the future, Moodle is going to turn it on by default.
See: https://tracker.moodle.org/browse/MDL-62352

Also, if you use the Moodle Log in as feature, the option will be forced on.
See: https://tracker.moodle.org/browse/MDL-63786

So, if we use Log in as feature, or we turn that option on in the Admin setting, WordSelect will be broken.

Thanks,

**Comment by marcusgreen** [comment]
I will monitor what is done with the STACK for how this might be fixed, and or get in touch with the OU people. I might come back to this in a couple of weeks during the Christmas break.

**Comment by HuongNV13** [comment]
Actually, I'm working on with this issue because the OU need this fix.

The patch will be provided soon.

**Comment by marcusgreen** [comment]
I hoped you would be :)
