### ISSUE TITLE
Word Select is not marking correct answers as correct for Students

### ISSUE THREAD

**Issue by valeriia-s** [marcusgreen/moodle-qtype_wordselect#27]
Hi @marcusgreen,

We are using the latest plugin version on Moodle 3.7. 
After the last version was released, we discovered the following issue.

While Word Select allows students to select an answer(s), it is not marking those that are correct, as correct. This issue happens only with the questions 1 and 3 that have additional HTML added to them (like `<br>` or `&nbsp;`). 

Here is how the question 1 looks like when I open an HTML editor (it has <br> tags):
​​
<img width="1100" alt="2020-02-28_1429" src="https://user-images.githubusercontent.com/29231219/75595324-b89e2480-5a40-11ea-84c0-7fc3a647c96c.png">
`[John Smith]<br> [Jane Smith]<br> John Smith, Jr.<br>[Sally Smith]<br>`

Here is my updated version - question 2 (without additional HTML):
<img width="1104" alt="2020-02-28_1434" src="https://user-images.githubusercontent.com/29231219/75595328-bf2c9c00-5a40-11ea-9ac4-a82eed56f11d.png">
`<p>[John Smith]</p><p>[Jane Smith]</p><p>John Smith, Jr</p><p>[Sally Smith]</p>`

Here is how the 3 question looks like when I open an HTML editor:
<img width="1109" alt="2020-02-28_1503" src="https://user-images.githubusercontent.com/29231219/75595351-d2d80280-5a40-11ea-9551-688be592b156.png">
`<p>Select the car that Sally Smith is allowed to drive under the policy.</p><p>&nbsp;Porsche</p><p>&nbsp;Mercedes</p><p>&nbsp;[Cabriolet]<br></p>`

Here is my updated version - question 4 (without additional HTML):
<img width="1105" alt="2020-02-28_15032" src="https://user-images.githubusercontent.com/29231219/75595364-e1261e80-5a40-11ea-8ac7-f6f2832fe59f.png">
`<p>Select the car that Sally Smith is allowed to drive under the policy.</p><p>Porsche</p<p>Mercedes</p><p>[Cabriolet]</p>`

When an Admin attempts this quiz, Word Select works as it should. Even with the additional HTML tags added:
<img width="389" alt="2020-02-28_1511" src="https://user-images.githubusercontent.com/29231219/75595382-fb5ffc80-5a40-11ea-83de-0a7f1cbbc46c.png">

However, here is what the Student role gets:
<img width="355" alt="2020-02-28_1512" src="https://user-images.githubusercontent.com/29231219/75595393-09ae1880-5a41-11ea-919b-6025d4d5cad2.png">

The text looks the same visually, however, the main difference is in HTML. The text was probably copied from an external editor and pasted into the Moodle Atto editor.

Please let me know if you need more details.

Thank you,
Valeriia

**Comment by marcusgreen** [comment]
Thank you for the detailed description. I will investsigate.

**Comment by marcusgreen** [comment]
Closing this issue. Release 2.43 included a fix for this which is documented in the release notes. Thanks for reporting this.
https://github.com/marcusgreen/moodle-qtype_wordselect/blob/master/changelog.md
