### ISSUE TITLE
Moodle 3.8.2 & Wordquiz

### ISSUE THREAD

**Issue by osworx** [marcusgreen/moodle-qtype_wordselect#28]
Hello, 
using latest version of Moodle, installed the plugin (module) via installer, can open the options in the administration, but I am not able to select this type of test.
Maybe I have overseen some and you could point me in the right direction?
Or are there any issues with the latest moodle version?

thx

**Comment by marcusgreen** [comment]
I don't understand your question.

**Comment by osworx** [comment]
> 
> 
> I don't understand your question.

Okay, again (maybe not in english)?

I have installed Moodle 3.8.2 (= latest official release).
Added via installer your module.
But I cannot select it!

I see it inside the section Plugins.
But when I want to create a Quiz, nothing, niente, nada - only the standard modules (came with the default Moodle installation).
Do you need more infos?

**Comment by marcusgreen** [comment]
Could you add a screen shot or the url from where you are trying to select it from, or the steps you took before you arrived at the issue.

**Comment by osworx** [comment]
Because you have to be a admin or manager, I don't know what an URL might help you (while I do not have any problem to provide such - but not publicity).
Screenshots are also possible, but from what?

And of course, you could also check that by yourself, if you contact me, I can send you the URL and give you access.

**Comment by marcusgreen** [comment]
That is an excellent idea. If you send me a username/password to a course with teacher access I can see what you can see. Send it to marcusgreen at mailbox.org

**Comment by marcusgreen** [comment]
Apparently no further feedback (or possibly email correspondence under a different name). Closing this, feel free to re-open, re-create if there is still an issue.
