### ISSUE TITLE
Minor typo in English language string

### ISSUE THREAD

**Issue by germanvaleroelizondo** [marcusgreen/moodle-qtype_wordselect#3]
Hi,

When I was trying your new wordselect plugin, I noticed a tiny typo in the English language string for pluginnamesummary:

'All words can be selected by clicking on them. Correct words are defined by surrounding with dlimiters e.g. The cat [sat] on the mat'

'dlimiters' should be 'delimiters ', I think.

Thanks for a very nice plugin.

**Comment by marcusgreen** [comment]
Thanks for spotting that, I have just fixed it
