### ISSUE TITLE
Language strings syntax not compatible with AMOS

### ISSUE THREAD

**Issue by mudrd8mz** [marcusgreen/moodle-qtype_wordselect#4]
At the moment, the strings parser at lang.moodle.org does not support strings concatenation operator (`.`) that is used for some of the strings (e.g. pluginname_help).

Please follow https://docs.moodle.org/dev/Plugin_contribution_checklist#Strings and have the string defined as one long literal value so that your plugin's string can be registered with AMOS. Thanks for understanding.

**Comment by marcusgreen** [comment]
Thanks for the feedback, I  will work on fixing that.

**Comment by marcusgreen** [comment]
Fixed in the latest release, thanks for letting me know.
