### ISSUE TITLE
'Missed' right answers

### ISSUE THREAD

**Issue by oucnelson** [marcusgreen/moodle-qtype_wordselect#40]
Hi Marcus,

This is some feedback from our activity designers.

Here's a dummy example I've just slung together to demonstrate the 'issue': students see the 'missed' right answers in square brackets.

![WS Moodle Core](https://user-images.githubusercontent.com/91731436/135607223-8a91e7d7-c50a-4444-ab3f-fcf5dc63668a.PNG)

So the suggestion for improvement is that 'missed' right answers are shown in maybe blue 'answer' boxes consistent with the correct/incorrect letters. Just my example, but the 8ED1FF background with black text seems to pass WCAG 2 AAA compliance for contrast:
 
![WS Moodle Core desired](https://user-images.githubusercontent.com/91731436/135608895-56c1d87e-a433-4c9f-ad26-b07fcebe924c.PNG)

Best wishes,

Chris.

**Comment by marcusgreen** [comment]
Thanks for the feedback, very pleased people are using this mode. I will read, absorb and experiment.

**Comment by oucnelson** [comment]
Apologies, Marcus, just noticed you'd release version 2.47. I installed that on our test server (we were 2.45), and now it shows as yellow:
![v2-47](https://user-images.githubusercontent.com/91731436/135613575-4d7dbd1f-a6f9-4886-85f0-df560316c46b.PNG)

**Comment by marcusgreen** [comment]
Excellent, I will close this ticket.  This was the origin of some of those updates.
https://moodle.org/mod/forum/discuss.php?d=416718#p1679175
