### ISSUE TITLE
Qurstion type on app not supported

### ISSUE THREAD

**Issue by Emanuel80** [marcusgreen/moodle-qtype_wordselect#43]
**Describe the bug**
I installed your question type (last version)  on my Moodle instance 3.9.6. I created a test quiz using you question and viaweb it works well, but when tested it on Moodle App (last releases on Google Play) and it say: This quiz can't be attempted in the app because it only contains question not supported by the app: wordselect

**Comment by marcusgreen** [comment]
I have tested the question type extensively on the mobile app and it does work. However there is an issue with mobile that it will return the error you are seeing when a new question type is installed and before the cache has been refreshed. I am closing this now, but if the problem did not resolve itself, re-open this ticket/create a new one and I will investigate further.
