### ISSUE TITLE
Word Select question when attempted, the Response history displays the submitted words in random order and without delimiters

### ISSUE THREAD

**Issue by AnupamaSarjoshi** [marcusgreen/moodle-qtype_wordselect#46]
Hi Marcus, 

We have seen the following issue. Could you please have a look? Thanks.

**Describe the bug**
When the WordSelect question is attempted as Admin, the Response history shows the submitted words in Random order and also there is no delimiter around the words to separate each one of them. This seems to be confusing when the submitted words have punctuation marks in them.

**To Reproduce**
Steps to reproduce the behaviour:
1. Login as Admin. Go to 'Question bank' and create a new Wordselect question
2. Preview and set the 'Response history' to Shown.
3. Attempt the question and select some words and click on 'Submit and finish'
4. Notice that in the Response history, the submitted words are displayed in Random order and also there is no delimiter around the words to separate each one of them. 

**Expected behaviour**
In the Response history the submitted words should be in order to the question text and also the words should be displayed within braces { } to clearly separate out the words selected.

**Screenshots**
![image](https://user-images.githubusercontent.com/81178902/174783179-c502fd21-a892-4482-b5e0-093f9e2b639f.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser Chrome
 - Wordselect Version: 2.48 on Moodle 3.11

**Comment by marcusgreen** [comment]
Am about to attempt to reproduce it locally

**Comment by rezeau** [comment]
Just tested this locally on my Moodle 4.0.1. _Works as expected_, The submitted words are in the same order as in the text. Agree with @AnupamaSarjoshi however that some kind of separator between those _submitted words_ (or groups of words) would be useful

**Comment by marcusgreen** [comment]
I wonder if however the core ddwtos question does it might be an inspiration...

**Comment by timhunt** [comment]
I can't work this out either, but I can confirm we are seeing this.

I don't believe the behaviour matters. I just reproduced the issue by previewing Anu's question on our system, and only afterwards notice that was using Interactive with multiple tries.

In case it helps, here is the question: (Github does not like XML files, so I had to rename to add .txt.)
[questions-U101-20B-WordSelect Reading Comprehension-20220622-1654.xml.txt](https://github.com/marcusgreen/moodle-qtype_wordselect/files/8959369/questions-U101-20B-WordSelect.Reading.Comprehension-20220622-1654.xml.txt)
 
There were bugs like this in the past in some core qtypes. Baiscally, when a DB server is new, then in theory, the order of results from any query will be random unless you specify an order-by. However, when DBs are new then typically rows are returned in id order at first, and then with time start getting more random. So, that might possibly explain this hard-to-reproduce bug ... except I just quickly looked at the code, and from what I can see, all the queries have an order-by id. (Example old bugs: MDL-27394 or [commit f07d1d319716a0b381ece29435c72999a798f778](https://github.com/moodle/moodle/commit/f07d1d319716a0b381ece29435c72999a798f778) - so old, it came before the tracker.)

More debugging needed, but I am out of time for today.

**Comment by marcusgreen** [comment]
Thanks for the feedback Tim. The behaviour thing was partly to ensure I was seeing exactly the same text before it showed the words, but as you suggest, that is probably not relevant. I was wondering about the order of stuff returned from the db, but I couldn't see how that would happen in this case. I will look further.

**Comment by marcusgreen** [comment]
I think the the order of the words returned is determined somewhere after here
https://github.com/marcusgreen/moodle-qtype_wordselect/blob/6183f72a45f9ad1d38742d4caed2c5e1d7d51883/question.php#L128

Possibly on the line that reads
            $matches = preg_split($fieldregex, $questiontextnodelim, null, PREG_SPLIT_DELIM_CAPTURE | PREG_SPLIT_NO_EMPTY);

**Comment by timhunt** [comment]
But the order of things returned from preg_split is always the order they were in the original string, so it is not clear how this could lead to the problem. It really is a mystery.

**Comment by marcusgreen** [comment]
I am closing this as I don't have the time to work towards a fix. If anyone comes up with a code fix I will be happy to review it.
