### ISSUE TITLE
Behat .feature files have the wrong tags

### ISSUE THREAD

**Issue by timhunt** [marcusgreen/moodle-qtype_wordselect#53]
This is the qtype_wordselect plugin.

It is not part of Moodle core, so the @core tag should not be present in any of the .feature files.

This is not mod_quiz or part of it, so the tags @mod @mod_quiz  should not be in any of the feature files.

**Comment by marcusgreen** [comment]
Thanks Tim, I will merge a pull or create it when I get back from Japan Moot Monday week. 

On another topic wordselect does not play nicely with filters at all.

**Comment by marcusgreen** [comment]
Removed the @core tags and merged. Closing issue.
