### ISSUE TITLE
Enhancement - Select AND define words

### ISSUE THREAD

**Issue by oliviervalentin** [marcusgreen/moodle-qtype_wordselect#54]
Dear Marcus,

thank you for your excellent plugin, which is very useful for our gramar teachers.
I often hear that they would like a precious feature : identify words according to some categories.

For exemple : in a sentence, we must seek and find pronouns and articles. But we must characterize each answer, that is not possible with Word Select.
As I know we can use several signs to surrond answers, do you think it would possible :
- to define some categories of words ?
- to make that each answer can be caracterized ? For exemple : do ONE click for first category, TWO clicks for second categories... ?

I didn't study all your codings, so I don't know if such a feature could be implemented easily.

Best regards, 
Olivier

**Comment by marcusgreen** [comment]
Hi Valentin, how does it compare with this idea from Tim Hunt?
https://github.com/marcusgreen/moodle-qtype_wordselect/issues/32
I was very interested in the concept, but I don't have time to work on it outside my day job.

**Comment by oliviervalentin** [comment]
Hi Marcus,
that is exactly what I was searching for. But I see your answer, and understand totally that it is difficult for you to add such a feature with your work aside.
And as you didn't add this before, I implicit understand that this would not be so easy to do ! :)
Too bad... hope I could one day do this by myself !
Olivier
