### ISSUE TITLE
JavaScript error with Moodle 4.5

### ISSUE THREAD

**Issue by mattgig** [marcusgreen/moodle-qtype_wordselect#56]
**Describe the bug**
Using the Word select question type in Moodle 4.5 creates a JavaScript errror in the console:

```
first.js:3960 Uncaught TypeError: $ is not a function
    at new WordSelectQuestion (first.js:3960:89)
    at Object.init (first.js:3960:916)
    at attempt.php?attempt=…cmid=27059:1183:109
    at Object.execCb (require.min.js:5:12861)
    at b.check (require.min.js:5:6615)
    at b.enable (require.min.js:5:9363)
    at b.init (require.min.js:5:5721)
    at require.min.js:5:11235
```

Because of this error, you want be able to mark (select) items in this question type.

**To Reproduce**
1. Create a quiz with a word select question.
2. Open the quiz with the question and try to select a word in the question.

**Expected behavior**
When clicking on a word, this should get selected.

**Screenshots**
![image](https://github.com/user-attachments/assets/67bbc01f-f040-4adf-ac1e-5d0d3c204040)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome, Brave, FireFox
 - Version newest

**Additional context**
The problem might be related to a problem seen with another plugin, see here for more information: https://github.com/brickfield/moodle-mod_board/pull/149/commits/97c800aed127a691c26cd1c9760b5e5628af2c7f

**Comment by rezeau** [comment]
I confirm @mattgig 's finding on my localhost moodle 4.5 test site!

**Comment by marcusgreen** [comment]
The OU generally doesn't look at compatibility with the latest version of Moodle for a while, so I will get on and investigate.

**Comment by rezeau** [comment]
Just tested before going to bed... it seems to work, at least it does not throw any error!
