### ISSUE TITLE
Problem when upgrading version

### ISSUE THREAD

**Issue by germanvaleroelizondo** [marcusgreen/moodle-qtype_wordselect#6]
Hi Marcus,
I had a problem when I tried to automatically (or manually) upgrade your wordselect plugin to the new 1.01 version.:

[new version available](https://cloud.githubusercontent.com/assets/2671923/18319273/988ae190-74ea-11e6-8e2d-f31fb79dde4e.png)

![installing available update](https://cloud.githubusercontent.com/assets/2671923/18319278/9ce44952-74ea-11e6-96c6-3dbf89f724de.png)

It goes into a loop and does not update the database .(

**Comment by germanvaleroelizondo** [comment]
See image:
![new version available](https://cloud.githubusercontent.com/assets/2671923/18319317/cc713158-74ea-11e6-96a0-9cc73565d7df.png)

**Comment by germanvaleroelizondo** [comment]
I have seen this problem in 2 different localhost 3.11 servers.

**Comment by germanvaleroelizondo** [comment]
When I un-installed the plugin and update the database, and later I install it, it shows VERSION 2016062500 is about to be installed.
Maybe there is a problem with the new ZIP file version naming...

**Comment by germanvaleroelizondo** [comment]
Issue fixed with plugin version 1.03 :)

**Comment by marcusgreen** [comment]
Thanks for the feedback German.
