### ISSUE TITLE
Allow phrase with special to be selected

### ISSUE THREAD

**Issue by lethevinh** [marcusgreen/moodle-qtype_wordselect#9]
![attachfilehandler](https://user-images.githubusercontent.com/6895930/36461998-5f9c6a78-16f3-11e8-9983-dd7a8edcbc80.png)

**Comment by lethevinh** [comment]
-All Words are formatting as Bold/Italic...Font Color..and all are not affected when using WordSelect . should we fix issue

**Comment by marcusgreen** [comment]
I don't quiet understand, are you saying you want them formatted and they are not formatted, or that they are formatted and you don't want them formatted?

**Comment by lethevinh** [comment]
i want them formatted and they are not formatted.

**Comment by marcusgreen** [comment]
OK I understand what you are asking now. You want selectable correct and incorrect text to be formatting as in the example you give. I am currently working on a version 2 of the plugin that I hope will support that possibility. The current code comes closer to that and I will bear you request in mind as I develop. My most recent work was to try to ensure that mathjax (maths) formatted text would be selectable.

**Comment by lethevinh** [comment]
Please , Review code and  let me know what you think.

**Comment by marcusgreen** [comment]
I was reviewing it  and creating a Unit test just as your message came in. I have taken your pad_angle_brackets modified it and added it to the branch I have been working on and it looks good. I will be adding text to the sample questions that demonstrates this capability.

**Comment by lethevinh** [comment]
Yes, thank you very much. Please let me know immediately the feedback or bug you found. I will fix them.

**Comment by marcusgreen** [comment]
I have just noticed you created a behat test, that is wonderful!

**Comment by marcusgreen** [comment]
Will be adding this unit test 
public function test_pad_angle_brackets(){
         $questiontext = '<p>The cat [<b>sat</b>]';
         $question = qtype_wordselect_test_helper::make_question('wordselect', $questiontext);
         $paddedquestiontext= $question::pad_angle_brackets($questiontext);
         /*note the gap added between <p> and The */
         $this->assertEquals($paddedquestiontext,"<p> The cat [<b>sat</b>]",'padding of html tags failed');
         /* tags retained are  'sub', 'sup', 'i', 'u', 'b' */
         $this->assertContains("[<b>sat</b>]",$paddedquestiontext,'formatting tags not retained ');
}

**Comment by lethevinh** [comment]
I have run your behat and unit test and smoke test. everything is fine.

**Comment by marcusgreen** [comment]
I have added big sections of your code and a credit for your work in the release notes file
https://github.com/marcusgreen/moodle-qtype_wordselect/blob/master/releasenotes.md

**Comment by marcusgreen** [comment]
Hi
My current plan is to update the little icon for the plugin and then release to the Moodle plugins database. I am not certain of the timescale yet.  I have set up a course with the current code for people to experiment with. 

http://vledevelop.co.uk/moodle/
You can log in as a teacher as
username:t1 password:test

**Comment by marcusgreen** [comment]
Would you email me directly at marcusavgreen at gmail dot com, as there is a question I would like to ask you.

**Comment by lethevinh** [comment]
Your new code looks good, but it still does not cover the word  with colors or some html attributes. <span style="color:red" > text </span>

**Comment by lethevinh** [comment]
current , not support the word from the colour format and format attribute html other, `<span class="" style="color: rgb(0, 61, 245);">text</span>` <span class="" style="color: rgb(0, 61, 245);">text</span>, please review my code part.

https://github.com/marcusgreen/moodle-qtype_wordselect/blob/14e4ab5567d937cb77814f9f3ff8f61e8c116aba/question.php#L188

` $questiontext = preg_replace_callback('/<([a-zA-Z]*)[ ]*([a-zA-Z0-9\# =\'\"\:\(\,\;\)]*)\>/', function($a) use
        ($tags) {`

**Comment by marcusgreen** [comment]
That looks very interesting. I will review and get back to you.

**Comment by marcusgreen** [comment]
Do you have an idea for how to support color?

**Comment by lethevinh** [comment]
I am waiting for your review, please let me know your feedback. please help me. thank you.

**Comment by marcusgreen** [comment]
CWhat am I reviewing, can you create a new pull?

**Comment by marcusgreen** [comment]
Ok, I have seen your pull. I am travelling at the moment (writing this on mobile phone). Will look more closely when I get home. What is kbd  by the way?

**Comment by lethevinh** [comment]
kbd tag is  keyboard input
https://www.w3schools.com/tags/tag_kbd.asp

**Comment by marcusgreen** [comment]
Did a small amount of testing and accepted your pull. Will update the example questions and and do some more testing before releasing a version 2.1. Excellent work.  The travis testing is broken because I have not set up the jshint correctly. Will work on configuring that.

**Comment by lethevinh** [comment]
thank you so much

**Comment by lethevinh** [comment]
thank you so much

**Comment by marcusgreen** [comment]
I am impressed with your contributions, could you email me at marcusavgreen@gmail.com. I may have something of interest to you.

**Comment by marcusgreen** [comment]
this code is now in the v2.1 release available from the plugins database at moodle org
https://moodle.org/plugins/qtype_wordselect

**Comment by marcusgreen** [comment]
Could you email me at marcusavgreen@gmail.com, I may have an opportunity for some paid Moodle work for you.
